### ISSUE TITLE
Info Configuration Screen

### ISSUE THREAD

**Issue by CristiHabliuc** [code4romania/de-urgenta-ios#11]
This has two variants:
- [ ] After validation ([Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1467%3A4556))
- [ ] Anytime after that ([Figma](https://www.figma.com/file/d6n3MPVRWbL5jP2NmvW96b/De_Urgenta?node-id=1472%3A2655))

**Comment by vladr11** [comment]
Iau eu info config.
